// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseManagementSystem.DAL.Data;

#nullable disable

namespace WarehouseManagementSystem.DAL.Migrations
{
    [DbContext(typeof(WarehouseManagementSystemDbContext))]
    [Migration("20260609112025_RestoreRestrictDeleteRules")]
    partial class RestoreRestrictDeleteRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseManagementSystem.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and accessories",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Warehouse furniture and storage solutions",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            Description = "General office supplies and equipment",
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            ProductId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 3,
                            ProductId = 3,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 4,
                            LastUpdated = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 4,
                            ProductId = 4,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            LastUpdated = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 3,
                            ProductId = 5,
                            Quantity = 255
                        },
                        new
                        {
                            Id = 6,
                            LastUpdated = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 3,
                            ProductId = 6,
                            Quantity = 500
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShelfNumber")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MDC-A-01",
                            ShelfNumber = 1,
                            WarehouseId = 1,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MDC-B-03",
                            ShelfNumber = 3,
                            WarehouseId = 1,
                            Zone = "B"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EFH-A-01",
                            ShelfNumber = 1,
                            WarehouseId = 2,
                            Zone = "A"
                        },
                        new
                        {
                            Id = 4,
                            Code = "EFH-C-06",
                            ShelfNumber = 6,
                            WarehouseId = 2,
                            Zone = "C"
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ProductReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Portable barcode scanner designed for fast and accurate inventory processing",
                            Name = "Handheld Barcode Scanner",
                            Price = 120.00m,
                            ProductReceivedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 0.35m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "High-speed thermal printer for warehouse and shipping labels",
                            Name = "Industrial Label Printer",
                            Price = 230m,
                            ProductReceivedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 2.10m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "15-inch laptop built for office productivity and warehouse administration",
                            Name = "Laptop",
                            Price = 1500m,
                            ProductReceivedAt = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 1.5m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Full HD monitor suitable for administrative and operational workstations",
                            Name = "Monitor",
                            Price = 300m,
                            ProductReceivedAt = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 3.0m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Adjustable office chair designed for long-duration seated work",
                            Name = "Ergonomic Office Chair",
                            Price = 250m,
                            ProductReceivedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 15m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Durable desk with ample surface area for office and warehouse coordination tasks",
                            Name = "Workstation Desk",
                            Price = 400m,
                            ProductReceivedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 30m
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PurchaseOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedDeliveryDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = 1001,
                            Status = 2,
                            SupplierId = 1,
                            TotalAmount = 29000m,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpectedDeliveryDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = 1002,
                            Status = 2,
                            SupplierId = 2,
                            TotalAmount = 51000m,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExpectedDeliveryDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            OrderNumber = 1003,
                            Status = 3,
                            SupplierId = 3,
                            TotalAmount = 20000m,
                            WarehouseId = 3
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            PurchaseOrderId = 1,
                            Quantity = 50,
                            UnitPrice = 120m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            PurchaseOrderId = 1,
                            Quantity = 100,
                            UnitPrice = 230m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            PurchaseOrderId = 2,
                            Quantity = 30,
                            UnitPrice = 1500m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            PurchaseOrderId = 2,
                            Quantity = 20,
                            UnitPrice = 300m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            PurchaseOrderId = 3,
                            Quantity = 40,
                            UnitPrice = 250m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            PurchaseOrderId = 3,
                            Quantity = 25,
                            UnitPrice = 400m
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactAddress = "910 Industrial Park Road, Chicago, USA",
                            ContactEmail = "michael.carter@autoidsystems.com",
                            ContactPerson = "Michael Carter",
                            ContactPhone = "+1-312-555-0142",
                            Name = "AutoID Systems"
                        },
                        new
                        {
                            Id = 2,
                            ContactAddress = "455 Technology Avenue, Columbus, USA",
                            ContactEmail = "laura.bennett@techcore.com",
                            ContactPerson = "Laura Bennett",
                            ContactPhone = "+1-614-555-0187",
                            Name = "TechCore Solutions"
                        },
                        new
                        {
                            Id = 3,
                            ContactAddress = "220 Business Center Drive, Phoenix, USA",
                            ContactEmail = "daniel.foster@officefurnishings.com",
                            ContactPerson = "Daniel Foster",
                            ContactPhone = "+1-602-555-0119",
                            Name = "Office Furnishings Group"
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1250 Logistics Parkway",
                            Capacity = 1000,
                            City = "Chicago",
                            Country = "USA",
                            Name = "Main Distribution Center"
                        },
                        new
                        {
                            Id = 2,
                            Address = "840 Industrial Avenue",
                            Capacity = 750,
                            City = "Columbus",
                            Country = "USA",
                            Name = "Eastern Fulfillment Hub"
                        },
                        new
                        {
                            Id = 3,
                            Address = "620 Commerce Drive",
                            Capacity = 500,
                            City = "Phoenix",
                            Country = "USA",
                            Name = "Western Logistics Center"
                        });
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Inventory", b =>
                {
                    b.HasOne("WarehouseManagementSystem.Model.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagementSystem.Model.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Location", b =>
                {
                    b.HasOne("WarehouseManagementSystem.Model.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Product", b =>
                {
                    b.HasOne("WarehouseManagementSystem.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.PurchaseOrder", b =>
                {
                    b.HasOne("WarehouseManagementSystem.Model.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagementSystem.Model.Warehouse", "Warehouse")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.PurchaseOrderItem", b =>
                {
                    b.HasOne("WarehouseManagementSystem.Model.Product", "Product")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagementSystem.Model.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Location", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Model.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
